### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by tj** [componentjs/component#423]
need to sit down and come up with the roadmap, thing like migrating to ES6 modules modules etc. still plenty of time for that until http 2.0 is reasonably adopted, but we'll want to have it ready for them because all this concatenation stuff is going to disappear.

Large changes:
- [ ] migration to es6 module syntax (requires publish to centralized registry for transformation)
- [ ] centralized registry with github-style namespacing
- [ ] auto-migration of all components to registry
- [ ] `component-publish(1)` command
- [ ] redo component.io for new registry backed by riak / s3
- [ ] rename / brand component (any suggestions?) I don't mind even "c8", then we can keep the component.io domain
- [ ] consider auto-prefixer for css on the registry end
