### ISSUE TITLE
release of 1.0.0

### ISSUE THREAD

**Issue by timaschew** [componentjs/component#601]
@clintwood @jasonkuhrt @netpoetica @trevorgerhardt @jonathanong 

what do you think to release 1.0.0? 

So we can do a list what we should fix for this version, for instance I saw a note here: https://github.com/componentjs/component/blob/master/History.md#100-rc4--2014-04-04

> Component 1.0.0 is now feature complete. Please help debug and open an issues you may have with this release! 1.0.0 will not be released until http://component.io is updated.
### TODO before release
- [x] update all internal components (builder2.js, etc.)
  - [x] builder2.js
  - [x] console.js
  - [x] resolver.js
- [x] [add tags for all  component/ repos to fix \* dependency / pin version](https://github.com/componentjs/component/issues/602) this become obsolete
- [x] merge https://github.com/componentjs/component/pull/596
- [x] [custom remotes](https://github.com/componentjs/guide/blob/master/changelogs/1.0.0.md#custom-remotes) 
- [x] check [".remotes is currently in flux and is pretty much broken. Don't set a .remotes array in your component.json for now!"](https://github.com/componentjs/guide/blob/master/changelogs/1.0.0.md#componentjson) can it be removed?
- [x] http://component.io [#587](https://github.com/componentjs/component/issues/587#issuecomment-55507830), fix [broken website url](https://github.com/componentjs/component.io/issues/80#issuecomment-56269835)
- [x] --standalone arg in combination with a component.json standalone property [#24](https://github.com/componentjs/guide/issues/24)
- [x] cannot require below the root [#22](https://github.com/componentjs/resolver.js/issues/22)
- [ ] test all CLI tools with args [component CLI API](https://github.com/componentjs/guide/blob/master/component/api.md#crawl)
- [x] docs
  - [x] refactor docs and links, split into docs for 0.x and 1.0
  - [x] check the spec [spec](https://github.com/componentjs/spec) - is it in sync with the implementation?
  - [x] update some links,etc. in the docs, like for github: remove _raw.github.com_
  - [x] show how to use the github token, instead of username and password
- [x] #573 don't exit watcher when syntax errors occur in scripts
- [x] https://github.com/componentjs/builder2.js/issues/29 locals ordering sometimes wrong
- [x] https://github.com/componentjs/builder2.js/issues/82
- [x] https://github.com/componentjs/builder2.js/issues/84
